### PR TITLE
Add rate switch to the ad hoc charting page

### PR DESCRIPTION
**Pull request by yaacov**
**Description**

Add a rate switch for charts in ad-hoc charts

**Screenshot**

gifrecord_2017-02-28_093923

Based on https://github.com/ManageIQ/manageiq-ui-classic/pull/449

### CODE REVIEW

**Comment by yaacov** [comment]
@miq-bot add_label providers/containers

@simon3z @zakiva @zeari @zgalor @himdel please review

**Comment by himdel** [comment]
@yaacov Only problem I can see is that the `%input` is not really a pair element, so the "Rate" text should live in a `%label` which includes both the `%input` and the text, on the same level..

**Comment by yaacov** [comment]
@himdel 👍 thanks, fixed

**Comment by simon3z** [comment]
ATM I have the feeling we should use the Hawkular API for this (which supports rates). This PR requires further discussion.

**Comment by yaacov** [comment]
> ATM I have the feeling we should use the Hawkular API for this (which supports rates). This PR requires further discussion.

@simon3z I tried to use the Hawkular API, because i thought the code will be cleaner, but it has some big cons:

1. more code, much more code :-(
2. more UI, we will have to tell the users that can't do rate on gages ...
3. less features:
    3.1 no rate for gauges.
    3.2 we can not chart gauges and counters on the same chart.

**Pull request closed without merging**
